version: '3'
services:
  php: &php
    image: shin1x1/php-dev:7.3-apache-buster
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
      - ./docker/php/httpd-php.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db
      - db-test
  php8:
    <<: *php
    image: shin1x1/php-dev:8.0-apache-buster
    ports:
      - "8001:80"
  composer:
    image: composer:2
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
  db: &db
    image: library/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=app
    volumes:
      - .:/opt:cached
  db-test:
    <<: *db
    ports:
      - "23306:3306"
