name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack and run test
      run: make
    - name: Run test on PHP 8
      run: make test-php8
